version: '3'
services:
  test-docker1:
    container_name: test-docker1
    build: 
      context: ./DockerImageTest1
    networks:
      - default
    expose:
      - 8089
    volumes:
      - ./host_volume:/home/my_volume
